const INITIALIZE_SQL_ERROR = '初始化 SQL 錯誤'
const GENERATE_SQL_ERROR = '參照檔案建立 SQL 錯誤'
const UPLOAD_SQL_FILE_ERROR = '上傳 SQL 檔案錯誤'
const NO_HIGHLIGHT_ERROR = 'No highlights at all.'

export { INITIALIZE_SQL_ERROR, GENERATE_SQL_ERROR, UPLOAD_SQL_FILE_ERROR, NO_HIGHLIGHT_ERROR }
